# -*- coding: utf-8 -*-
"""Titanic_Survivors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MT2Oclp1xD0SqsgQxAeEKxs9PbwKx_r1

# TITANIC SURVIVORS ANALYSIS
"""

import pandas as pd
import numpy as np

"""# READING DATA USING PANDAS
We use pandas read_csv funtion to read the csv file in python and pandas DataFrame method to convert file into the data frame.
"""

df = pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head()

"""Description of the attributes of the dataset

Pclass: Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)

name: Name

sex: Sex

age: Age

sibsp: Number of Siblings/Spouses Aboard

parch: Number of Parents/Children Aboard

ticket: Ticket Number

fare: Passenger Fare (British pound)

cabin: Cabin

embarked: Port of Embarkation (C = Cherbourg; Q = 
Queenstown; S = Southampton)

# Count the Number of Passenger Survived
"""

df['Survived'].value_counts()

"""Total Number of Passengers Survived :- 342

# Count the Number of Passenger Survived by different columns
"""

df.groupby(['Pclass'])['Survived'].value_counts()

"""* Number of 1st Class Passenger Survived :- 136
* Number of 2nd Class Passenger Survived :- 87
* Number of 3rd Class Passenger Survived :- 119
"""

df.groupby(['Sex'])['Survived'].value_counts()

"""* Number of Female Survived :- 233
* Number of Male Survived :- 109
"""

df['FamilySize'] = df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'],axis = 1,inplace = True)
df['Alone'] = ["Not Alone" if df['FamilySize'][i]>0 else "Alone" for i in df.index]
df.groupby(['Alone'])['Survived'].value_counts()

"""* Number of Alone Passengers Survived :- 163
* Number of Family Passengers Survived :- 179
"""

df.groupby(['Embarked'])['Survived'].value_counts()

"""* Number of Cherbourg Passengers Survived :- 93
* Number of Queenstown Passengers Survived :- 30
* Number of Southampton Passengers Survived :- 217

# CONCLUSION
* Total Number of Passengers Survived :- 342
1. 1st Class Passengers have higher survival rate than othes.
2. 3rd Class Passengers have higher survival rate than 2nd Class Passengers
3. Female Passengers were prioritized over Male Passengers
4. Passengers with their family have higher survival rate.
5. Passengers who bored the ship at Southampton have higher survival rate than others.
6. Passengers who bored the ship at Queenstown have lower survival rate than others.
"""